name: Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Zip integration
        run: |
          cd custom_components/fightcade
          zip -r ../../fightcade.zip .
      - uses: softprops/action-gh-release@v2
        with:
          files: fightcade.zip
          generate_release_notes: true
